version: '3'
services:
  nest-authentication-ytb-db:
    container_name: nest-authentication-ytb-db
    image: postgres:13.4-alpine
    environment:
      - 'POSTGRES_DB=nest_authentication_ytb'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'